training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 100
  validation_split: 0.2
  early_stopping_patience: 10

augmentation:
  rotation_range: 10
  width_shift_range: 0.1
  height_shift_range: 0.1
  horizontal_flip: False
  brightness_range: [0.9, 1.1]
